export enum ErrorCodeEnum {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Register
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT',
  USERNAME_TOO_LONG = 'USERNAME_TOO_LONG',
  USERNAME_MUST_BE_ALPHANUMERIC = 'USERNAME_MUST_BE_ALPHANUMERIC',
  USERNAME_REQUIRED = 'USERNAME_REQUIRED',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Unit
  UNIT_CREATE_FAILED = 'UNIT_CREATE_FAILED',
  UNIT_UPDATE_FAILED = 'UNIT_UPDATE_FAILED',
  UNIT_DELETE_FAILED = 'UNIT_DELETE_FAILED',
  UNIT_NOT_FOUND = 'UNIT_NOT_FOUND',
  FAILED_GET_ALL_UNITS = 'FAILED_GET_ALL_UNITS',

  // Material
  MATERIAL_CREATE_FAILED = 'MATERIAL_CREATE_FAILED',
  MATERIAL_UPDATE_FAILED = 'MATERIAL_UPDATE_FAILED',
  MATERIAL_DELETE_FAILED = 'MATERIAL_DELETE_FAILED',
  MATERIAL_NOT_FOUND = 'MATERIAL_NOT_FOUND',
  FAILED_GET_ALL_MATERIALS = 'FAILED_GET_ALL_MATERIALS',

  // Stock
  STOCK_CREATE_FAILED = 'STOCK_CREATE_FAILED',
  STOCK_UPDATE_FAILED = 'STOCK_UPDATE_FAILED',
  STOCK_DELETE_FAILED = 'STOCK_DELETE_FAILED',
  STOCK_NOT_FOUND = 'STOCK_NOT_FOUND',
  FAILED_GET_ALL_STOCKS = 'FAILED_GET_ALL_STOCKS',
  QUANTITY_MUST_BE_POSITIVE = 'QUANTITY_MUST_BE_POSITIVE',
  MINIMUM_CANNOT_EXCEED_MAXIMUM = 'MINIMUM_CANNOT_EXCEED_MAXIMUM',
  MAXIMUM_CANNOT_BE_LESS_THAN_MINIMUM = 'MAXIMUM_CANNOT_BE_LESS_THAN_MINIMUM',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
